"""Per-collection articulation map for corpus pitches outside General MIDI.

``drum_roles`` covers General MIDI percussion pitches 35-81.  The drum libraries
in this corpus place hi-hat articulations in a low band around pitches 19-27, so
under the General MIDI map alone roughly a quarter of the corpus note mass falls
into ``other_percussion`` and the lane carrying the rhythmic subdivision is lost.

This module resolves a pitch to a canonical role using a map keyed by collection,
generated by ``scripts/build_articulation_map.py`` from measured evidence.  A
pitch with no entry for its collection falls back to the General MIDI map, which
keeps unjustified pitches in ``other_percussion`` rather than guessing.

The map is advisory data for the training projection only.  ``groove.hvo.v2`` and
the shipped retrieval seed do not use it and are unaffected.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .drum_roles import GM_DRUM_ROLE_BY_PITCH, GM_DRUM_ROLES

_MAP_PATH = Path(__file__).with_name("articulation_map.json")

ArticulationEntry = dict[str, Any]


def _load_map(path: Path) -> dict[str, ArticulationEntry]:
    raw: object = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("articulation map must be an object")
    loaded: dict[str, ArticulationEntry] = {}
    for collection, entry in raw.items():
        if not isinstance(collection, str) or not isinstance(entry, dict):
            raise ValueError("articulation map entries must be keyed objects")
        pitches = entry.get("pitches", {})
        if not isinstance(pitches, dict):
            raise ValueError(f"articulation map for {collection!r} has no pitch table")
        resolved: dict[int, str] = {}
        for pitch, role in pitches.items():
            if not isinstance(role, str) or role not in GM_DRUM_ROLES:
                raise ValueError(f"articulation map for {collection!r} names unknown role {role!r}")
            resolved[int(pitch)] = role
        loaded[collection] = {
            "pitches": resolved,
            "confidence": str(entry.get("confidence", "unknown")),
            "evidence": str(entry.get("evidence", "")),
        }
    return loaded


_ARTICULATION_MAP: dict[str, ArticulationEntry] = _load_map(_MAP_PATH)


def mapped_collections() -> frozenset[str]:
    """Return the collections that carry an articulation override."""

    return frozenset(_ARTICULATION_MAP)


def collection_confidence(collection: str) -> str | None:
    """Return the recorded confidence for a collection, or None when unmapped."""

    entry = _ARTICULATION_MAP.get(collection)
    return None if entry is None else str(entry["confidence"])


def resolve_role(collection: str, pitch: int) -> str:
    """Resolve one pitch to a canonical drum role for a given collection.

    Falls back to the General MIDI map whenever the collection has no override
    for the pitch, so an unjustified pitch stays in ``other_percussion``.
    """

    entry = _ARTICULATION_MAP.get(collection)
    if entry is not None:
        pitches: dict[int, str] = entry["pitches"]
        role = pitches.get(pitch)
        if role is not None:
            return role
    return GM_DRUM_ROLE_BY_PITCH.get(pitch, "other_percussion")


__all__ = [
    "collection_confidence",
    "mapped_collections",
    "resolve_role",
]
